#!/usr/bin/env bash

success () {
    printf "\r\033[2K  [ \033[00;32mOK\033[0m ] %s\n" "$1"
}

git submodule update --init

# zsh-syntax-highlighting
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git

# zsh
cp .zshrc ~/.zshrc

# vim
cp .vimrc ~/.vimrc

# git
cp .gitconfig ~/.gitconfig
cp .git-completion.bash ~/.git-completion.bash

echo ''
success 'All installed!'