#!/usr/bin/env bash

SERVER=false

success () {
    printf "\r\033[2K  [ \033[00;32mOK\033[0m ] %s\n" "$1"
}

link_files() {
    if [ -L "$2" ] ; then
        rm -f "$2"
    fi

    ln -s "$(pwd)/$1" "$2"
    success "linked $1 to $2"
}

while [[ $# -gt 0 ]]; do
  key="$1"

  case $key in
    -s|--server)
    SERVER=true
    ;;

    *)
    ;;
  esac
  shift
done

if ${SERVER}; then
  success "SERVER mode enabled!"
  echo ''
fi

git submodule update --init

CONFIG_DIR=~/.config
mkdir -p "${CONFIG_DIR}"

if ! ${SERVER}; then
  # i3
  link_files config/Xresources ~/.Xresources
  link_files config/i3/config "${CONFIG_DIR}"/i3/config
  link_files config/polybar/config "${CONFIG_DIR}"/polybar/config
  link_files config/rofi/config "${CONFIG_DIR}"/rofi/config 
  link_files config/rofi/nord.rasi "${CONFIG_DIR}"/rofi/nord.rasi 
  link_files config/dunst/dunstrc "${CONFIG_DIR}"/dunst/dunstrc 
  xrdb ~/.Xresources

  # terminal
  link_files config/terminator/config "${CONFIG_DIR}"/terminator/config
  link_files config/terminator/gtk.css "${CONFIG_DIR}"/gtk-3.0/gtk.css

  # vim
  link_files vim/vimrc ~/.ideavimrc
fi

# ranger
link_files config/ranger "${CONFIG_DIR}"/ranger

# Oh My Zsh
[ ! -d "$HOME/.oh-my-zsh" ] && sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# zsh
mkdir -p ~/.zsh
link_files zsh/aliases ~/.aliases
rm -rf ~/.zshrc && link_files zsh/zshrc ~/.zshrc
link_files zsh/zsh-syntax-highlighting ~/zsh-syntax-highlighting
link_files zsh/zsh-autosuggestions ~/.zsh/zsh-autosuggestions
link_files zsh/pure ~/.zsh/pure

# vim
link_files vim ~/.vim
link_files vim/vimrc ~/.vimrc
link_files vim/nvim ~/.config/nvim

# git
link_files git/gitconfig ~/.gitconfig
link_files git/gitignore_global ~/.gitignore_global

# tmux
link_files tmux.conf ~/.tmux.conf

echo ''
success 'All installed!'
