#!/usr/bin/env bash

# solarized8
git clone https://github.com/lifepillar/vim-solarized8.git ~/.vim/pack/themes/opt/solarized8

# zsh-syntax-highlighting
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git
echo "source ${(q-)PWD}/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh" >> ${ZDOTDIR:-$HOME}/.zshrc

# zsh
cp .zshrc ~/.zshrc

# vim
cp .vimrc ~/.vimrc

# git
cp .gitconfig ~/.gitconfig
cp .git-completion.bash ~/.git-completion.bash

echo ''
echo '  All installed!'