syntax on
set mouse=a
filetype plugin indent on

set background=dark

colorscheme solarized8

set title

" Hide buffer instead of abandoning when unloading
set hidden

" Enhanced command line completion
set wildmenu
" Complete files like a shell
set wildmode=list:longest
set wildignore=.svn,CVS,.git,.hg,*.o,*.a,*.class,*.mo,*.la,*.so,*.obj,*.swp,*.xpm,*.pyc,*.pyo,*.log

" Show line numbers
set number
" Show cursor position
set ruler
" Show current line
set cursorline
" Highlight matches as you type
set incsearch
" Highlight matches
set hlsearch
" set case insensitivity
set ignorecase
" unless there's a capital letter
set smartcase
" Turn on line wrapping
set wrap
" Show 3 lines of context around the cursor
set scrolloff=3

" No beeping
set visualbell
" abbrev. of messages (avoids 'hit enter')
set shortmess+=filmnrxoOtT

" Don't make a backup before overwriting a file
set nobackup
" And again
set nowritebackup
" Use an SCM instead of swap files
set noswapfile

" Show the status line all the time
set laststatus=2

" http://vim.wikia.com/wiki/Backspace_and_delete_problems
set backspace=indent,eol,start

set expandtab

set autoindent
" copy the previous indentation on autoindenting
set copyindent
" use multiple of shiftwidth when indenting with '<' and '>'
set shiftround
" set show matching parenthesis
set showmatch

" Read vim config defined in files
set modeline
set modelines=1

" command and search pattern history
set history=10000

" make plugins smoother
set lazyredraw

" always replace all occurences of a line
set gdefault

" http://vim.wikia.com/wiki/Toggle_auto-indenting_for_code_paste
set pastetoggle=<F2>

" disable folding
set nofoldenable

" Tabs and indentation
set autoindent
set smartindent
set tabstop=2
set shiftwidth=2
set softtabstop=2

inoremap {      {}<Left>
inoremap {<CR>  {<CR>}<Esc>O
inoremap {{     {
inoremap {}     {}

" Copy
vnoremap <C-c> yi

" Paste
nnoremap <C-v> pi
inoremap <C-v> <ESC>pi

" Cut
vnoremap <C-x> xi

" Undo
nnoremap <C-z> <nop>
vnoremap <C-z> <nop>
inoremap <C-z> <nop>

nnoremap <C-z> u
vnoremap <C-z> u
inoremap <C-z> <C-O>u

" Make the view port scroll faster
nnoremap <C-e> 3<C-e>
nnoremap <C-y> 3<C-y>
nnoremap <C-p> 3<C-p>

" Text selection
nmap <S-Up> v
nmap <S-Down> v
nmap <S-Left> v
nmap <S-Right> v
imap <S-Up> <esc>v
imap <S-Down> <esc>v
imap <S-Left> <esc>v
imap <S-Right> <esc>v
vmap <S-Up> k
vmap <S-Down> j
vmap <S-Left> h
vmap <S-Right> l

" Select all
map <C-a> <esc>ggVG<CR>

" Backspace
nnoremap <BS> xi
vnoremap <BS> xi

" Change cursor shape between insert and normal mode in iTerm2.app
if $TERM_PROGRAM =~ "iTerm"
    let &t_SI = "\<Esc>]50;CursorShape=1\x7" " Vertical bar in insert mode
    let &t_EI = "\<Esc>]50;CursorShape=0\x7" " Block in normal mode
endif

"" Plugins

" airline
let g:airline_theme = 'luna'
let g:airline_extensions = ['branch', 'whitespace']
set noshowmode

" NERDTree
" autocmd vimenter * NERDTree
map <C-n> :NERDTreeToggle<CR>
