syntax enable
set mouse=a

" True color support {{{

"Credit joshdick
"Use 24-bit (true-color) mode in Vim/Neovim when outside tmux.
"If you're using tmux version 2.2 or later, you can remove the outermost $TMUX check and use tmux's 24-bit color support
"(see < http://sunaku.github.io/tmux-24bit-color.html#usage > for more information.)
"if (empty($TMUX))
  if (has("nvim"))
    "For Neovim 0.1.3 and 0.1.4 < https://github.com/neovim/neovim/pull/2198 >
    let $NVIM_TUI_ENABLE_TRUE_COLOR=1
  endif
  "For Neovim > 0.1.5 and Vim > patch 7.4.1799 < https://github.com/vim/vim/commit/61be73bb0f965a895bfb064ea3e55476ac175162 >
  "Based on Vim patch 7.4.1770 (`guicolors` option) < https://github.com/vim/vim/commit/8a633e3427b47286869aa4b96f2bfc1fe65b25cd >
  " < https://github.com/neovim/neovim/wiki/Following-HEAD#20160511 >
  if (has("termguicolors"))
    set termguicolors
  endif
"endif

" }}}

" Plugins {{{
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')

Plug 'preservim/nerdtree'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'tpope/vim-fugitive'
Plug 'airblade/vim-gitgutter'
Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }
Plug 'editorconfig/editorconfig-vim'
Plug 'joshdick/onedark.vim'
Plug 'ghifarit53/tokyonight-vim'
Plug 'sheerun/vim-polyglot'
Plug 'fabi1cazenave/termopen.vim'
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'pechorin/any-jump.vim'
" post install (yarn install | npm install) then load plugin only for editing supported files
Plug 'prettier/vim-prettier', { 'do': 'yarn install --frozen-lockfile --production' }

call plug#end()
" }}}

" Colors {{{
let g:tokyonight_style = 'night' " available: night, storm
let g:tokyonight_enable_italic = 1
colorscheme tokyonight

let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#formatter = 'default'
let g:airline#extensions#tabline#show_close_button = 0 " remove 'X' at the end of the tabline
let g:airline#extensions#tabline#tabs_label = ''       " can put text here like BUFFERS to denote buffers (I clear it so nothing is shown)
let g:airline#extensions#tabline#buffers_label = ''    " can put text here like TABS to denote tabs (I clear it so nothing is shown)
let g:airline#extensions#tabline#show_tab_count = 0    " dont show tab numbers on the right
let g:airline#extensions#tabline#show_buffers = 0      " dont show buffers in the tabline
let g:airline#extensions#tabline#show_splits = 0       " disables the buffer name that displays on the right of the tabline
let g:airline#extensions#tabline#show_tab_nr = 0       " disable tab numbers
let g:airline#extensions#tabline#fnamemod = ':t'       " disable file paths in the tab

" }}}

" Spaces & Tabs {{{
set tabstop=2           " number of visual spaces per TAB
set softtabstop=2       " number of spaces in tab when editing
set expandtab           " tabs are spaces
" }}}

" UI Config {{{
set number              " show line numbers
set cursorline          " highlight current line
filetype indent on      " load filetype-specific indent files
set wildmenu            " visual autocomplete for command menu
set lazyredraw          " redraw only when we need to.
set showmatch           " highlight matching [{()}]
set splitbelow          " split to bottom
"set splitright         " split to right
" }}}

" Searching {{{
set incsearch           " search as characters are entered
set hlsearch            " highlight matches
" }}}

" Folding {{{
set foldenable          " enable folding
set foldlevelstart=10   " open most folds by default
set foldnestmax=10      " 10 nested fold max
set foldmethod=indent   " fold based on indent level
"nnoremap za za     " space open/closes folds
" }}}

" Leader shortcuts {{{
let mapleader=" "       " leader is space
"inoremap ze <esc>       " ze is escape
"vnoremap ze <esc>       " ze is escape
" }}}

" Backups {{{
set nobackup            " Don't make a backup before overwriting a file
set nowritebackup       " And again
set noswapfile          " Use an SCM instead of swap files
" }}}

" Other {{{
set autoindent
"set idearefactormode=keep
" }}}

" Key bindings {{{

" Term Open {{{
  nmap <Leader>r :call TermOpenRanger('ranger', 't')<CR>
" }}}

" FZF {{{
nnoremap <C-p> :Files<CR>
inoremap <C-p> <Esc>:Files<CR>
nnoremap <C-f> :BLines<CR>
inoremap <C-f> <Esc>:BLines<CR>
nnoremap <Leader>f :Rg<CR>

let g:fzf_buffers_jump = 1
let g:fzf_action = {
\ 'ctrl-t': 'tab split',
\ 'ctrl-x': 'split',
\ 'ctrl-v': 'vsplit' }
" }}}

" Nerdtree {{{
nnoremap <C-b> :NERDTreeToggle<CR>
inoremap <C-b> <Esc>:NERDTreeToggle<CR>i
vnoremap <C-b> :NERDTreeToggle<CR>
map <leader>b :NERDTreeFind<CR>

" Open in new tab when double clicking on file in Nerdtree
autocmd VimEnter * call NERDTreeAddKeyMap({ 'key': '<2-LeftMouse>', 'scope': "FileNode", 'callback': "OpenInTab", 'override':1 })
function! OpenInTab(node)
    call a:node.activate({'reuse': 'all', 'where': 't'})
endfunction
" }}}

" Copy {{{
vnoremap <C-c> "+y
nnoremap Y yg$
" }}}

" Paste {{{
vnoremap p pgvy
" }}}

" Text selection {{{
nnoremap <S-Up> v<UP>
nnoremap <S-Down> v<DOWN>
nnoremap <S-Left> v<LEFT>
nnoremap <S-Right> v<RIGHT>
inoremap <S-Up> <Esc>v<UP>
inoremap <S-Down> <Esc>v<DOWN>
inoremap <S-Left> <Esc>v<LEFT>
inoremap <S-Right> <Esc>v<RIGHT>
vnoremap <S-Up> k
vnoremap <S-Down> j
vnoremap <S-Left> h
vnoremap <S-Right> l
" }}}

" Backspace {{{
set backspace=indent,eol,start
nnoremap <BS> i<BS><Esc>
vnoremap <BS> <Del>i
" }}}

" Find and replace {{{
nnoremap <C-h> <esc>:%s///g
inoremap <C-h> <esc>:%s///g
" }}}

" Duplicate line {{{ 
nnoremap <C-d> <Esc>mayyp`a<Down>
inoremap <C-d> <Esc>mayyp`a<Down>i<Right>
vnoremap <C-d> y'>p
" }}}

" Move lines {{{
nnoremap <A-j> :m .+1<CR>==
nnoremap <A-k> :m .-2<CR>==
inoremap <A-j> <Esc>:m .+1<CR>==gi
inoremap <A-k> <Esc>:m .-2<CR>==gi
vnoremap <A-j> :m '>+1<CR>gv=gv
vnoremap <A-k> :m '<-2<CR>gv=gv
"}}}

" Save {{{
nnoremap <C-s> :w<CR>
vnoremap <C-s> <Esc>:w<CR>
inoremap <C-s> <C-o>:w<CR><Esc>
" }}} 

" Enter {{{
nnoremap <CR> i<CR><Esc>
" }}}

" Quit {{{
nnoremap <C-w> :q<CR>
inoremap <C-w> <Esc>:q<CR>
vnoremap <C-w> :q<CR>
"}}}

" GoDef tab {{{
au FileType go nmap gd <Plug>(go-def-tab)
" }}}

" Other remap {{{
nnoremap m $
nnoremap n nzzzv
nnoremap N Nzzzv
nnoremap J mzJ`z
" }}}

" Undo {{{
inoremap , ,<C-g>u
inoremap . .<C-g>u
inoremap ! !<C-g>u
inoremap ? ?<C-g>u
" }}}

" }}}

" Change cursor in Insert/Normal mode
let &t_SI = "\e[6 q"
let &t_EI = "\e[2 q"

" Hide ~
"set fillchars=fold:\ ,vert:\│,eob:\ ,msgsep:‾
let &fcs='eob: '

set modeline
set modelines=1
" vim:foldmethod=marker:foldlevel=0
