#!/bin/bash

if [ ${OSTYPE} = "linux-gnu" ] || [ ${OSTYPE} = "linux-gnueabi" ]; then
  alias ls='ls --color'
  alias ll='ls -Flh --group-directories-first'
  alias la='ls -Flah --group-directories-first'
  alias pbcopy="xclip -selection clipboard"
else
  alias ls='ls -G'
  alias ll='gls -Flh --group-directories-first --color'
  alias la='gls -Flah --group-directories-first --color'
fi

alias open='xdg-open'
alias cd..="cd .."
alias ..="cd .."
alias grep='grep --color=auto'
alias pbcopy='wl-copy'
alias pubkey="cat ~/.ssh/id_rsa.pub | pbcopy"
alias publicip='curl ifconfig.me'
alias r="ranger"
alias update="sudo apt update && apt list --upgradable"
alias upgrade="sudo apt upgrade"
alias port="netstat -ntpl | grep $@"
alias killport="sudo lsof -i :$1 | awk '{print \$2}' | awk 'FNR == 2 {print}' | sudo xargs kill -9"
alias wip='gaa && gcmsg "wip"'

alias dotfiles='cd ~/Lab/github/dotfiles'
alias sogilis='cd ~/Lab/Sogilis'
alias planbot='cd ~/Lab/Sogilis/planbot'

function initnvm {
  export NVM_DIR="$HOME/.nvm"
  [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"                    # This loads nvm
  [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" # This loads nvm bash_completion
}

