# Functions Autoloading
fpath=(~/.zsh $fpath)
fpath+=$HOME/.zsh/pure

# Completion
autoload -U promptinit && promptinit
autoload -U compinit compdef && compinit

# Prompt
prompt pure

# Variables
export EDITOR='vim'
export GIT_EDITOR='vim'
export SHELL='/bin/zsh'
export GREP_COLOR=31
export PROJECTS_FOLDER=~/Lab/Sites/cisco
export GOPATH=${PROJECTS_FOLDER}/golang
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# History
HISTFILE="$HOME/.history"
HISTSIZE=100000
SAVEHIST="$HISTSIZE"

# -----------
# - Plugins -
# -----------
source ~/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh

# ----------------------
# - User configuration -
# ----------------------

# Correction des commandes
setopt histignorealldups sharehistory
unsetopt correctall
setopt autocd

# Remove superfluous blanks from each command line being added to the history
# list
setopt histreduceblanks
# Remove command lines from the history list when the first character on the
# line is a space, or when one of the expanded aliases contains a leading space
setopt histignorespace
# Do not enter command lines into the history list if they are duplicates of the
# previous event.
setopt histignorealldups
# Switching directories for lazy people
setopt autocd
# See: http://zsh.sourceforge.net/Intro/intro_6.html
setopt autopushd pushdminus pushdsilent pushdtohome pushdignoredups
# Don't kill background jobs when I logout
setopt nohup
# See: http://zsh.sourceforge.net/Intro/intro_2.html
setopt extendedglob
# Do not require a leading '.' in a filename to be matched explicitly
setopt globdots
# Use vi key bindings in ZSH
setopt vi
# Causes field splitting to be performed on unquoted parameter expansions
setopt shwordsplit
# Automatically use menu completion after the second consecutive request for
# completion
setopt automenu
# If the argument to a cd command (or an implied cd with the AUTO_CD option set)
# is not a directory, and does not begin with a slash, try to expand the
# expression as if it were preceded by a '~'
setopt cdablevars
# Try to make the completion list smaller (occupying less lines) by printing
# the matches in columns with different widths
setopt listpacked
# Don't show types in completion lists
setopt nolisttypes
# If a completion is performed with the cursor within a word, and a full
# completion is inserted, the cursor is moved to the end of the word
setopt alwaystoend
# Try to correct the spelling of commands
setopt correct

# case-insensitive (uppercase from lowercase) completion
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'

# process completion
zstyle ':completion:*:processes' command 'ps -au$USER'
zstyle ':completion:*:*:kill:*:processes' list-colors "=(#b) #([0-9]#)*=36=31"

# zstyle
zstyle ':completion:*' completer _expand _complete _ignored _approximate
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' menu select=2
zstyle ':completion:*' select-prompt '%SScrolling active: current selection at %p%s'
zstyle ':completion:*:descriptions' format '%U%F{yellow}%d%f%u'
zstyle ':completion:*:*:git:*' script ~/.git-completion.bash

# -----------
# - ALIASES -
# -----------

if [[ "$TERM_PROGRAM" != "" && "$TERM_PROGRAM" != "iTerm.app" ]]
then
  alias ls='ls --color'
else
  alias ls='ls -G'
fi

alias ll='ls -lth | grep "^d" && ls -lth | grep -v "^d"'
alias la='ls -lath | grep "^d" && ls -lhta | grep -v "^d"'
alias open='xdg-open'
alias nmap='nmap -T4 -A -v $1'
alias cd..="cd .."
alias ..="cd .."
alias grep='grep --color=auto'
alias gpul='git pull'
alias gpus='git push'
alias gco='git co'
alias gci='git ci -m'
alias gst="git st"
alias preview="fzf --preview 'cat {}'"
alias pbcopy="xclip -selection clipboard"
alias pubkey="cat ~/.ssh/id_rsa.pub | pbcopy"
alias mackb="xmodmap -e 'keycode 94=at numbersign' -e 'keycode 49=less greater less greater less greater'"
alias rails='f() { docker-compose -p web-test exec -T sqsc sh -c "bundle exec rails $1 $2 $3" };f'
alias publicip='curl ifconfig.me'

## CISCO aliases
alias cisco='cd ~/Lab/Sites/cisco'
alias webapp-v3='cd ~/Lab/Sites/cisco/webapp-v3'
alias sbs-syncd='cd ~/Lab/Sites/cisco/golang/src/sentryo.net/sbs-syncd'
function startv3-lc {
  webapp-v3
  sudo rm -f build/v2
  sudo rm -f public/v2
  sudo ln -sf ../../webapp-v2/dist public/v2
  sudo rm -Rf build/
  REACT_APP_BACKEND_PROXY=$(docker container port sbs-syncd_lc_1 8080) yarn start
}
function startv3-gc {
  webapp-v3
  sudo rm -f build/v2
  sudo rm -f public/v2
  sudo ln -sf ../../webapp-v2/dist public/v2
  sudo rm -Rf build/
  REACT_APP_BACKEND_PROXY=$(docker container port sbs-syncd_gc_1 8080) yarn start
}

# -----------
# - Exports -
# -----------
export PATH="/usr/local/bin:$PATH"
export PATH="/home/bdumas/go/bin:$PATH"
export PATH="$PATH:./node_modules/.bin"

# NVM
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" # This loads nvm bash_completion

# ------------
# - Bindkeys -
# ------------

## fzf - ^R - Search
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

bindkey "[D" backward-word
bindkey "[C" forward-word

bindkey "^A" beginning-of-line
bindkey "^E" end-of-line

bindkey "^[[1;5C" forward-word
bindkey "^[[1;5D" backward-word

## phpbrew
# export PHPBREW_SET_PROMPT=1
# [[ -e ~/.phpbrew/bashrc ]] && source ~/.phpbrew/bashrc

# DOCKER ALIAS
# alias docker-drush='docker run --rm --link local.dev -v $(pwd):/app drush/drush:8 $1'
# alias docker-apache='docker exec -it web-apache-7 bash'
# alias docker-into-mysql='docker exec -it local.localhost mysql -h local.localhost -u root -proot'
# alias docker-mysql='docker exec local.localhost mysql $1'
# alias docker-restart='cd ~/lab/docker-preferences && docker-compose down && docker-compose up -d && cd -'
# alias docker-start='cd ~/lab/docker-preferences && docker-compose up -d && cd -'
# alias docker-stop='cd ~/lab/docker-preferences && docker-compose down && cd -'
