# Variables
export EDITOR='vim'
export GIT_EDITOR='vim'
export SHELL='/bin/zsh'
export GREP_COLOR=31
#export PROJECTS_FOLDER=~/Lab/Sites/cisco
export PROJECTS_FOLDER=~/projects
export GOPATH=${PROJECTS_FOLDER}/golang
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export ZSH="$HOME/.oh-my-zsh"
export FZF_ALT_C_OPTS="--preview 'tree -C {} | head -200'"

ZSH_THEME=""

# History
HISTFILE="$HOME/.history"
HISTSIZE=100000
SAVEHIST="$HISTSIZE"

# -----------
# - Plugins -
# -----------
plugins=(git)
source $ZSH/oh-my-zsh.sh
source ~/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh

# Pure prompt
fpath+=$HOME/.zsh/pure
autoload -U promptinit; promptinit
prompt pure

# ----------------------
# - User configuration -
# ----------------------

# Correction des commandes
setopt histignorealldups sharehistory
unsetopt correctall
setopt autocd
# Remove superfluous blanks from each command line being added to the history
# list
setopt histreduceblanks
# Remove command lines from the history list when the first character on the
# line is a space, or when one of the expanded aliases contains a leading space
setopt histignorespace
# Do not enter command lines into the history list if they are duplicates of the
# previous event.
setopt histignorealldups
# Switching directories for lazy people
setopt autocd
# See: http://zsh.sourceforge.net/Intro/intro_6.html
setopt autopushd pushdminus pushdsilent pushdtohome pushdignoredups
# Don't kill background jobs when I logout
setopt nohup
# See: http://zsh.sourceforge.net/Intro/intro_2.html
setopt extendedglob
# Do not require a leading '.' in a filename to be matched explicitly
setopt globdots
# Use vi key bindings in ZSH
setopt vi
# Causes field splitting to be performed on unquoted parameter expansions
setopt shwordsplit
# Automatically use menu completion after the second consecutive request for
# completion
setopt automenu
# If the argument to a cd command (or an implied cd with the AUTO_CD option set)
# is not a directory, and does not begin with a slash, try to expand the
# expression as if it were preceded by a '~'
setopt cdablevars
# Try to make the completion list smaller (occupying less lines) by printing
# the matches in columns with different widths
setopt listpacked
# Don't show types in completion lists
setopt nolisttypes
# If a completion is performed with the cursor within a word, and a full
# completion is inserted, the cursor is moved to the end of the word
setopt alwaystoend
# Try to correct the spelling of commands
setopt correct

# -----------
# - ALIASES -
# -----------
source $HOME/.aliases

# -----------
# - Exports -
# -----------
export PATH="/usr/local/bin:$PATH"
export PATH="/usr/local/go/bin:$PATH"
export PATH="$GOPATH/bin:$PATH"
export PATH="$PATH:./node_modules/.bin"

# ------------
# - Bindkeys -
# ------------
## fzf - ^R - Search
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

bindkey -v
bindkey "[D" backward-word
bindkey "OD" backward-word
bindkey ";3D" backward-word
bindkey "^[^[[D" backward-word
bindkey "^[b" backward-word

bindkey "OC" forward-word
bindkey "[C" forward-word
bindkey ";3C" forward-word
bindkey "^[^[[C" forward-word
bindkey "^[f" forward-word

bindkey "^A" beginning-of-line
bindkey "^E" end-of-line

[ -f ~/.hadesrc ] && source ~/.hadesrc

# Disable Software Flow Control (Ctrl-S)
# https://superuser.com/questions/1390977/pressing-ctrl-s-by-mistake-while-using-vim
stty stop ""

initnvm
nvm use stable
